name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2
        
      - name: Mocha install
        run: |
          cd src;
          npm install -g mocha;
          npm install;
          
      - name: Run test
        run: mocha src/test/convert.js
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags: |
            gabriel9820/conversao-temperatura:v1
            gabriel9820/conversao-temperatura:latest
