name: CI

on:
  #triggers
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-lastest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16.13.2
    
